### ISSUE TITLE
Lesson 2 script doesn't run - no parameter file

### ISSUE THREAD

**Issue by jamedina09** [NGEET/fates-tutorial#54]
### Description:
I tried the first exercise on two different Mac computers (Sonoma 14.6.1) and the script `./create_elm-fates-singlepoint-1pft_bci_invinit.sh` doesn't run. The issue seems to be related to the missing parameter file `fates_params_default-1pft.nc`. After manually copying and modifying the necessary parameter file to the `paramfiles` directory within the container, the model runs without any problems.

### Steps to Reproduce:
1. Clone the FATES tutorial repository and navigate into it

2. Create and modify the `.env` file:
    ```bash
    cp env-template .env
    code .env
    ```

*Note:* for INPUT_DATA I'm pointing to the inventory_data folder within the fates tutorial repo

3. Download the Docker images:
    ```bash
    docker compose up -d
    ```

4. Run the container:
    ```bash
    docker exec -it elm-fates /bin/bash
    ```

5. Check for the parameter file `fates_params_default-1pft.nc`:
    ```bash
    cd paramfiles
    ls
    ```

    **Problem:** The parameter file is not there

6. Try running the script:
    ```bash
    cd ../scripts/
    ./create_elm-fates-singlepoint-1pft_bci_invinit.sh
    ```

    **Problem:** The log shows the following error message:
    ```
    ERROR: GETFIL: FAILED to get /paramfiles/fates_params_default-1pft.nc
    ```

7. Manually copy the required files from the FATES directory within the container:
    ```bash
    cp /E3SM/components/elm/src/external_models/fates/parameter_files/fates_params_default.cdl /paramfiles
    cp /E3SM/components/elm/src/external_models/fates/tools/FatesPFTIndexSwapper.py /paramfiles
    ```

    *Note:* This also copies the files to the host machine's `param_files/` directory as expected.

8. Prepare the parameter file with only 1 PFT:
    ```bash
    cd ../paramfiles/
    ncgen -o fates_params_default.nc fates_params_default.cdl
    python ./FatesPFTIndexSwapper.py --fin fates_params_default.nc --fout fates_params_default-1pft.nc --pft-indices 1
    ```

9. Run the script again:
    ```bash
    cd ../scripts/
    ./create_elm-fates-singlepoint-1pft_bci_invinit.sh
    ```

    **Success:** Lesson 2 works as expected.

### Expected Behavior:
As the first exercise, the user may expect that the script ./create_elm-fates-singlepoint-1pft_bci_invinit.sh runs without any issue.

### System Information:
- OS: macOS Sonoma 14.6.1
- Docker version: 27.1.1, build 6312585

**Comment by JessicaNeedham** [comment]
@jamedina09 thanks for spotting this! The plan was to have the single pft parameter file be already in  the param directory so that the run would just work. Manipulating parameter files comes later in the tutorial. 

@glemieux I guess at this point since people will have already set up docker and downloaded the FATES tutorial it might make sense to move the lessons around so that this parameter file manipulation happens before the first run? Or we could fix the volume to contain that parameter file and get them to delete the volume before docker compose up?

**Comment by JessicaNeedham** [comment]
I've moved some slides around so now people will have to generate the single PFT parameter file before launching the first run. I think that should  work ok.

**Comment by glemieux** [comment]
Thanks @jamedina09 for testing this out and providing a detailed replication.  Thanks @JessicaNeedham, I agree this is the easiest thing to do currently.
