### ISSUE TITLE
cd command issue - possible solution

### ISSUE THREAD

**Issue by jamedina09** [NGEET/fates-tutorial#56]
### Minor minor bug:
I've just came across the 'cd' behaviour inside docker (Greg mentioned this before). This is minor as users can type type 'cd /' to go to the root directory. But it would be nice (I think) to have the default behaviour of 'cd' to go to the root directory.

### Showing the issue with the 'cd' command in the Docker container
 Start the Docker Compose services in detached mode
```bash
docker compose up -d
```

 Access the running Docker container with an interactive bash shell
```bash
docker exec -it elm-fates /bin/bash
```

Navigate to a directory within the container
```bash
cd tools/
```

- The command prompt displays:
modeluser@docker:/tools$

 Change to the home directory (default behavior of 'cd' with no arguments)
```bash
cd
```

- The command prompt moves to the home directory:
modeluser@docker:~$

### Possible solution to make the 'cd' command return to the root directory when no arguments are given
Open a new terminal and access the Docker container again
```bash
docker exec -it elm-fates /bin/bash
```

 Edit the user's .bashrc file with vim
```bash
vim ~/.bashrc
```

 Enter Insert Mode in vim
```bash
i
```

 Add a custom cd function to .bashrc
```bash
cd() {
    if [ -z "$1" ]; then
        builtin cd /
    else
        builtin cd "$1"
    fi
}
```

 Exit Insert Mode
```bash
Esc
```

 Save and exit vim
```bash
:wq
```

 Apply the changes made to .bashrc
```bash
source ~/.bashrc
```

 Navigate to a directory within the container again
```bash
cd tools/
```

 Change to the home directory (this should now take you to the root directory)
```bash
cd
```

### Success:
- The command prompt now displays:
 modeluser@docker:/$

- That 'cd' function could be included by default

**Comment by glemieux** [comment]
This looks like a great workaround for the time being.  Thanks @jamedina09.  I'm going to build it into the image and have the attendees repull the fates container on Monday.  I've made a commit to the tutorial-containers repo to add this: https://github.com/NGEET/tutorial-containers/commit/724809582d0e97e0e4a7fd9afa2b62ea8df4223c.  I'll give you a heads up once I rebuild and push it to dockerhub

**Comment by glemieux** [comment]
New build is up on dockerhub and should be working.  I'm testing it with the bci run script now.

**Comment by glemieux** [comment]
Build looks good.  The new `cd` function appears to work as expected!

**Comment by jamedina09** [comment]
I just tested it too. It works smoothly. Thanks.
